INSERT INTO categorie (libelle)
VALUES ('Fruits et légumes'),
  ('Boucherie et volaille'),
  ('Charcuterie traiteur'),
  ('Poissonnerie'),
  ('Crèmerie'),
  ('Fromagerie'),
  ('Boulangerie - pâtisserie'),
  ('Produits surgelés'),
  ('Épicerie'),
  ('Petit déjeuner'),
  ('Produits laitiers'),
  ('Boissons'),
  ('Produits bio'),
  ('Confiserie'),
  ('Produits pour les enfants et bébés'),
  ('Produits de beauté'),
  ('Produits d''hygiène et de soins'),
  ('Produits d''entretien'),
  ('Produits pour animaux'),
  ('Maison et divers'),
  ('Autres');